export default {
  'Append EndEvent': '追加结束事件',
  'Append Gateway': '追加网关',
  'Append Task': '追加任务',
  'Cancel': '取消',
  'Close': '关闭',
  'Create EndEvent': '结束',
  'Create Gateway': '网关',
  'Create Task': '任务',
  'Create StartEvent': '开始',
  'Create UserTask': '审批任务',
  'Create ParallelGateway': '并行网关',
  'Create ExclusiveGateway': '互斥网关',
  'Create CallActivity': '子流程',
  'Data Object': '数据对象',
  'Data Store': '数据存储',
  'EndEvent': '结束',
  'Error EndEvent': '错误结束',
  'Event': '事件',
  'ExclusiveGateway': '互斥网关',
  'Gateway': '网关',
  'InclusiveGateway': '包容网关',
  'Intermediate Throw Event': '中间抛出事件',
  'Message EndEvent': '消息结束',
  'Message StartEvent': '消息开始',
  'ParallelGateway': '并行网关',
  'Process': '流程',
  'Receive Task': '接收任务',
  'Script Task': '脚本任务',
  'Send Task': '发送任务',
  'SequenceFlow': '连线',
  'Service Task': '服务任务',
  'StartEvent': '开始',
  'Sub Process': '子流程',
  'Task': '任务',
  'Timer StartEvent': '定时开始',
  'Transaction': '事务',
  'UserTask': '审批任务',
  'Call Activity': '子流程',
  'Add Lane above': '上方添加泳道',
  'Divide into two Lanes': '分割泳道',
  'Remove': '删除',
  'Append': '追加',
  'Delete': '删除',
  'Connect': '连线',
  'diagram': '流程图',
  'Name': '名称',
  'Id': '标识',
  'General': '通用',
  'Variables': '变量',
  'Forms': '表单',
  'Extensions': '扩展',
  'Multi Instance': '多实例',
  'Execution Listener': '执行监听器',
  'Listeners': '监听器',
  'Sequence Flow': '连线',
  'Condition': '条件',
  'Condition Expression': '条件表达式',
  'Default Flow': '默认流',
  'Source': '来源',
  'Target': '目标',
  'Change type': '更改类型',
  'Connect using': '连接到',
  'connected to': '已连接到',
  'Element': '元素',
  'Properties': '属性',
  'Details': '详情',
  'Documentation': '说明',
  'Add': '添加',
  'Edit': '编辑',
  'Assignee': '处理人',
  'Candidate Users': '候选人',
  'Candidate Groups': '候选组',
  'Due Date': '截止日期',
  'Priority': '优先级',
  'called element': '子流程ID',
  'Wait for completion': '等待完成',
  'Asynchronous Before': '异步前置',
  'Asynchronous After': '异步后置',
  'Job Execution': '作业执行',
  'Exclusive': '互斥',
  'is startable in tasklist': '可在任务列表启动',
  'History Cleanup': '历史清理',
  'Startable': '可启动',
  'Multi-instance': '多实例',
  'Loop Characteristics': '循环特性',
  'Sequential': '顺序（单签）',
  'Parallel': '并行（会签）',
  'Loop Cardinality': '循环基数',
  'Collection': '集合',
  'Element Variable': '元素变量',
  'Completion Condition': '完成条件',
  'Asynchronous': '异步',
  'Form Key': '表单Key',
  'Form fields': '表单字段',
  'Business Key': '业务Key',
  'Task Listener': '任务监听器',
  'Listener': '监听器',
  'Event Type': '事件类型',
  'Listener Type': '监听器类型',
  'Java Class': 'Java类',
  'Expression': '表达式',
  'Delegate Expression': '代理表达式',
  'Fields': '字段',
  'Field Name': '字段名',
  'String': '字符串',
  'String Value': '字符串值',
  'Expression Value': '表达式值',
  'Value': '值',
  'Parameter': '参数',
  'In': '输入',
  'Out': '输出',
  'Input Parameter': '输入参数',
  'Output Parameter': '输出参数',
  'Source Variable': '源变量',
  'Target Variable': '目标变量',
  'Business Key Expression': '业务Key表达式',
  'Variables Mapping': '变量映射',
  'Process Variables': '流程变量',
  'Error Code': '错误码',
  'Error Message': '错误信息',
  'Retry Time Cycle': '重试周期',
  'Timer Definition Type': '定时器类型',
  'Timer Definition': '定时器定义',
  'Date': '日期',
  'Duration': '时长',
  'Cycle': '周期',
  'End Date': '结束日期',
  'Start Date': '开始日期',
  'Repeat': '重复',
  'Time Cycle': '周期',
  'Time Date': '日期',
  'Time Duration': '时长',
  'Message': '消息',
  'Message Name': '消息名称',
  'Signal': '信号',
  'Signal Name': '信号名称',
  'Escalation': '升级',
  'Compensation': '补偿',
  'Error': '错误',
  'Errors': '错误',
  'Error Ref': '错误引用',
  'Error Name': '错误名称',
  'Error Code Variable': '错误码变量',
  'Error Message Variable': '错误信息变量',
  'Process Key': '流程Key',
  'Initiator': '发起人',
  'Form Data': '表单数据',
  'Form Property': '表单属性',
  'Text': '文本',
  'Number': '数字',
  'Boolean': '布尔',
  'Datetime': '日期时间',
  'Long': '长整型',
  'Double': '双精度',
  'Default Value': '默认值',
  'Enum Values': '枚举值',
  'Choices': '选项',
  'Choice': '选项',
  'Label': '标签',
  'Type': '类型',
  'Required': '必填',
  'Read Only': '只读',
  'Validation': '验证',
  'Constraints': '约束',
  'Max Length': '最大长度',
  'Min Length': '最小长度',
  'Pattern': '正则',
  'Maximum': '最大值',
  'Minimum': '最小值',
  'Decimal': '小数',
}
